Repository zscaler/zscaler-sdk-go, pull requests merged in 2023-01, with the labels that each got.

#62 Added omitempty to bool parameters in urlfiltering
  zia/services/urlfilteringpolicies/urlfilteringpolicies.go
Labels: bug

#63 Added omitempty to filteringrule fulllogging
  zia/services/firewallpolicies/filteringrules/filteringrules.go
Labels: bug

#64 Added New ZPA Inspection Control Parameters
  CHANGELOG.md
  zpa/services/inspectioncontrol/inspection_custom_controls/zpa_inspection_custom_controls.go
  zpa/services/inspectioncontrol/inspection_predefined_controls/zpa_inspection_predefined-controls.go
  zpa/services/inspectioncontrol/inspection_profile/zpa_inspection_profile.go
Labels: documentation, enhancement

#65 get all pages for zia resources
  zia/services/adminuserrolemgmt/adminusers.go
  zia/services/common/common.go
  zia/services/devicegroups/devicegroups.go
  zia/services/dlp_engines/dlp_engines.go
  zia/services/dlp_notification_templates/dlp_notification_templates.go
  zia/services/dlp_web_rules/dlp_web_rules.go
  zia/services/dlpdictionaries/dlpdictionaries.go
  zia/services/firewallpolicies/filteringrules/filteringrules.go
  zia/services/firewallpolicies/ipdestinationgroups/ipdestinationgroups.go
  zia/services/firewallpolicies/ipsourcegroups/ipsourcegroups.go
  zia/services/firewallpolicies/networkapplications/networkapplicationgroups.go
  zia/services/firewallpolicies/networkservices/networkservicegroups.go
  zia/services/firewallpolicies/networkservices/networkservices.go
  zia/services/firewallpolicies/timewindow/timewindow.go
  zia/services/intermediatecacertificates/intermediatecacertificates.go
  zia/services/locationmanagement/locationgroups/locationgroups.go
  zia/services/locationmanagement/locationmanagement.go
  zia/services/rule_labels/rule_labels.go
  zia/services/trafficforwarding/gretunnels/gretunnels.go
  zia/services/trafficforwarding/staticips/staticips.go
  zia/services/trafficforwarding/virtualipaddresslist/virtualipaddresslist.go
  zia/services/trafficforwarding/vpncredentials/vpncredentials.go
  zia/services/urlcategories/urlcategories.go
  zia/services/urlfilteringpolicies/urlfilteringpolicies.go
  zia/services/usermanagement/department.go
  zia/services/usermanagement/users.go
Labels: bug

#66 Get all pages for groups
  zia/services/usermanagement/group.go
Labels: bug

#67 Fix FW Enable Full Logging
  zia/services/firewallpolicies/filteringrules/filteringrules.go
Labels: bug

#68 Added new zia dlp endpoints
  CHANGELOG.md
  zia/services/dlp_engines/dlp_engines.go
  zia/services/dlp_icap_servers/dlp_icap_server.go
  zia/services/dlp_icap_servers/service.go
  zia/services/dlp_idm_profiles/dlp_idm_profiles.go
  zia/services/dlp_idm_profiles/service.go
  zia/services/dlp_incident_receiver_servers/dlp_incident_receiver_servers.go
  zia/services/dlp_incident_receiver_servers/service.go
  zia/services/dlp_notification_templates/dlp_notification_templates.go
  zia/services/dlp_web_rules/dlp_web_rules.go
Labels: enhancement
