Repository zscaler/zscaler-sdk-go, pull requests merged in 2023-03, with the labels that each got.

#77 (feat) New policy platform endpoint
  zpa/services/policysetcontroller/policysetclienttypes.go
  zpa/services/policysetcontroller/policysetcontroller.go
  zpa/services/policysetcontroller/policysetplatform.go
Labels: enhancement

#79 Added zdx program examples
  examples/zdx/reports/devices/README.md
  examples/zdx/reports/users/README.md
  zdx/services/reports/applications/application_score_metrics.go
  zdx/services/reports/applications/applications.go
Labels: documentation

#80 add segment group filters microtenantId & skipDetailedAppInfo
  zpa/services/applicationsegment/zpa_application_segment.go
  zpa/services/common/common.go
  zpa/services/segmentgroup/zpa_segment_group.go
  zpa/services/serviceedgegroup/zpa_service_edge_group.go
Labels: enhancement

#82 Added missing app segment attributes
  CHANGELOG.md
  zpa/services/applicationsegment/zpa_application_segment.go
  zpa/services/applicationsegmentinspection/zpa_application_segment_inspection.go
  zpa/services/applicationsegmentpra/zpa_application_segment_pra.go
  zpa/services/browseraccess/zpa_browser_access.go
Labels: enhancement

#73 Added AuthMethods to usermanagement
  zia/client.go
  zia/client_test.go
  zia/config.go
  zia/services/usermanagement/users.go
Labels: enhancement

#83 (feat) New zpa platform and clienttype endpoints
  zpa/services/clienttypes/clienttypes.go
  zpa/services/clienttypes/service.go
  zpa/services/platforms/platforms.go
  zpa/services/platforms/service.go
Labels: enhancement

#85 (fix) Added new Auth Attribs to zia Location Mgmt
  CHANGELOG.md
  zia/services/locationmanagement/locationmanagement.go
Labels: enhancement

#86 [fix] fix: ZPA IDP Controller New Attributes
  CHANGELOG.md
  zpa/services/idpcontroller/zpa_idp_controller.go
Labels: bug

#89 [FIX] refresh expired token & reduce number of items per page to avoid exceeding max response size
  zpa/client.go
Labels: bug, enhancement

#95 merge PRs #90 and #91
  zpa/client.go
Labels: enhancement

#93 (feat) Add support to sublocation search function
  zia/services/locationmanagement/locationmanagement.go
Labels: enhancement
