Repository zscaler/zscaler-sdk-go, pull requests merged in 2023-05, with the labels that each got.

#123 Improve searching for scim values by fitlerting with search query
  CHANGELOG.md
  zpa/services/scimattributeheader/zpa_scim_attribute_header.go
Labels: enhancement

#124 (feat) Added ZIA DLP Exact Data Match Schema
  CHANGELOG.md
  zia/services/dlp_exact_data_match/dlp_exact_data_match.go
  zia/services/dlp_exact_data_match/service.go
Labels: enhancement

#126 (Fix) ZPA API Client New Exception Handling
  CHANGELOG.md
  zpa/config.go
Labels: bug, enhancement

#127 (Fix) Fix ZPA Service Edge resource Struct type
  .gitignore
  CHANGELOG.md
  zpa/services/serviceedgecontroller/zpa_service_edge_controller.go
  zpa/services/serviceedgegroup/zpa_service_edge_group.go
Labels: bug
